#!/bin/sh

# functions for sharebox test suite

sharebox()
{
    $PWD/../sharebox $@
}

mkfs()
{
    [[ $1 == "-t" ]] && [[ $2 == "sharebox" ]] || exit 1
    shift 2
    $PWD/../mkfs.sharebox $@
}

fuse_tester()
{
    $PWD/lib/fuse_tester $@
}

clean()
{
    chmod -R +w sandbox
    rm -rf sandbox
}

assert_success()
{
    res=$($@ 2>&1)
    if [[ $? -ne 0 ]]; then
        echo "Error: the command '$@' failed, printing:"
        echo "$res"
        echo "Press enter to continue"
        read anykey
    fi
}

assert_fail()
{
    res=$($@ 2>&1)
    if [[ $? -eq 0 ]]; then
        echo "Error: the command '$@' succeeded, printing:"
        echo "$res"
        echo "Press enter to continue"
        read anykey
    fi
}
