#!/bin/sh

# functions for sharebox test suite

if test $1; then
    interactive=1
fi

sharebox()
{
    $PWD/../sharebox $@
}

mkfs()
{
    [[ $1 == "-t" ]] && [[ $2 == "sharebox" ]] || exit 1
    shift 2
    $PWD/../mkfs.sharebox $@
}

fuse_tester()
{
    $PWD/lib/fuse_tester $@
}

clean()
{
    chmod -R +w sandbox
    rm -rf sandbox
}

debug_interrupt()
{
    if test $interactive; then
        echo "Press enter to continue."
        read anykey
    fi
}

assert_success()
{
    ($@ 2>&1) >/dev/null || echo "Error: This failed: $@"
}

assert_fail()
{
    ($@ 2>&1) >/dev/null && echo "Error: This succeeded: $@"
}

